### ISSUE TITLE
bgp.tools

### ISSUE THREAD

**Issue by arshambh** [NoAnyNameForMe/SNI-Checker#1]
سلام و احترام
ممنون برای زحمتی کشیدید
میشه لطفا راهنمایی کنید که در سرچ باکس سایت bgp.tools مثلا چی وارد کنم که بهم فهرستی از دامنه هارو بده؟
تشکر

**Comment by NoAnyNameForMe** [comment]
> سلام و احترام ممنون برای زحمتی کشیدید میشه لطفا راهنمایی کنید که در سرچ باکس سایت bgp.tools مثلا چی وارد کنم که بهم فهرستی از دامنه هارو بده؟ تشکر

سلام، میتونید از این آموزش استفاده کنید
https://telegra.ph/آموزش-یافتن-SNI-برای-استفاده-با-رئالیتی-05-11
