### ISSUE TITLE
txt file

### ISSUE THREAD

**Issue by AliHemmati79** [NoAnyNameForMe/SNI-Checker#10]
سلام خسته نباشید، وقتی فایل txt وارد میکنم با همچین خطایی مواجه میشم!
مشکل از چی میتونه باشه؟

![py](https://github.com/NoAnyNameForMe/SNI-Checker/assets/99415271/278dca31-0433-4cbb-b9ca-d2fce871e3e0)

**Comment by NoAnyNameForMe** [comment]
آدرس فایل txt رو کامل وارد کنید.
مثال: C:\Users\Admin\Desktop\SNI\file.txt
