### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by amg9898** [NoAnyNameForMe/SNI-Checker#2]
همه رو انجام دادم فایل تکست هم طبق اون روش بهش معرفی کردم میخواستم ران کنم اولین سوال tls1.3 بود y زدم یهو شل بسته شد

**Comment by NoAnyNameForMe** [comment]
سلام.

به دلیل اینکه در قسمت Speed Test ورژن 1.3 یک سری مشکلات برای تعدادی وجود داشت و برای تعدادی خیر، این قسمت فعلا در کد حذف میشود.

به زودی قسمت Speed Test را با کانفیگ Reality، منتشر میکنم که کانفیگ را با SNI های چک شده تست بگیرد.

کد در گیت هاب جایگزین شد.

عذر خواهی میکنم بابت مشکلاتی که داشت.

**Comment by amg9898** [comment]
متاسفانه الان اسم فایل رو میزنم بسته میشه
