### ISSUE TITLE
اشکال در خواندن فایل تکست

### ISSUE THREAD

**Issue by f4r3ingh75** [NoAnyNameForMe/SNI-Checker#3]
سلام، اولا ممنون بابت اسکریپتی که نوشتین و ممنون بابت وقتی که میذارین تا مردم به اینترنت آزاد دسترسی داشته باشن.
من طبق آموزشی که دادین میرم ولی وقتی اسکن میکنم از فایل تکست فقط خط اول دامنه رو میخونه و باقی خطوط رو اسکن نمیکنه یا نمیخونه؟
حتی یکی دو خط بعدی رو پاک کردم (با خودم فکر کردم شاید مشکل از دامنه اوناست) ولی بازم مشکل حل نشد.
لطفا در این مورد راهنمایی کنین.

**Comment by NoAnyNameForMe** [comment]
سلام.

زمان هایی پیش میاد که روی بعضی از دامنه ها چندینبار تست گرفته میشه تا مطمعا بشه که مشکل داره.

این رو حتما فیکس میکنم که زمانی دامنه ای Timeout زیادی داشت Skip بشه.

**Comment by F4r3in** [comment]
سلام ممنون بابت پاسخگویی اینو من چک کردم و فهمیدم که چرا فایل تکست منو نمیخوند.
وقتی که از سایت گفته شده آدرس ها رو کپی میکنیم به فایل تکست، بین آی پی و دامنه در هر سطر یک اسپیس و یک تب میفته که اگر اون اسپیس رو پاک کنیم مشکل حل میشه و برنامه میتونه پینگ تمام دامنه ها رو بگیره.

**Comment by amg9898** [comment]
من اسپیس هم پاک کردم متاسفانه شل تا اسم فایل رو میزنم بسته میشه

**Comment by amg9898** [comment]
> > من اسپیس هم پاک کردم متاسفانه شل تا اسم فایل رو میزنم بسته میشه
> 
> ببین من کل فاصله بین آی پی و دامنه رو پاک نمیکنم. به اندازه یه تب نگه میدارم. یعنی برا من اینجوریه که وقتی از سایت میریزم تو تکست، یدونه اسپیس و یدونه تب داره که من فقط اون اسپیس رو پاک میکنم. به نظرم نویسنده کد میتونه برنامه رو اینجوری بنویسه که ما فقط آی پی سرورمون رو بدیم و خود برنامه بره از سایت دامنه ها رو برداره. من خودمم برنامه نویس حرفه ای نیستم ولی میدونم که با کتابخونه پانداس و دستور read_html میشه جدول های موجود در سایت رو خوند. در مورد بسته شدن شل باید بگم که من خودم اینجوری برنامه رو ران می کنم: میرم پوشه مسیر برنامه و اون بالا که آدرس پوشه هست رو پاک می کنم و میزنم cmd بعد دستور زیر رو مینوسم: python script_name اون script_name همون اسم فایل اسکریپت هست و بعد برنامه ران میشه. برای من تا برنامه تموم نشده صفحه بسته نمیشه.

منم همین هارو زدم نشده متاسفانه

**Comment by NoAnyNameForMe** [comment]
> > من اسپیس هم پاک کردم متاسفانه شل تا اسم فایل رو میزنم بسته میشه
> 
> ببین من کل فاصله بین آی پی و دامنه رو پاک نمیکنم. به اندازه یه تب نگه میدارم. یعنی برا من اینجوریه که وقتی از سایت میریزم تو تکست، یدونه اسپیس و یدونه تب داره که من فقط اون اسپیس رو پاک میکنم. به نظرم نویسنده کد میتونه برنامه رو اینجوری بنویسه که ما فقط آی پی سرورمون رو بدیم و خود برنامه بره از سایت دامنه ها رو برداره. من خودمم برنامه نویس حرفه ای نیستم ولی میدونم که با کتابخونه پانداس و دستور read_html میشه جدول های موجود در سایت رو خوند. در مورد بسته شدن شل باید بگم که من خودم اینجوری برنامه رو ران می کنم: میرم پوشه مسیر برنامه و اون بالا که آدرس پوشه هست رو پاک می کنم و میزنم cmd بعد دستور زیر رو مینوسم: python script_name اون script_name همون اسم فایل اسکریپت هست و بعد برنامه ران میشه. برای من تا برنامه تموم نشده صفحه بسته نمیشه.

حتما در آینده اضافه خواهم کرد.

**Comment by NoAnyNameForMe** [comment]
> > > من اسپیس هم پاک کردم متاسفانه شل تا اسم فایل رو میزنم بسته میشه
> > 
> > 
> > ببین من کل فاصله بین آی پی و دامنه رو پاک نمیکنم. به اندازه یه تب نگه میدارم. یعنی برا من اینجوریه که وقتی از سایت میریزم تو تکست، یدونه اسپیس و یدونه تب داره که من فقط اون اسپیس رو پاک میکنم. به نظرم نویسنده کد میتونه برنامه رو اینجوری بنویسه که ما فقط آی پی سرورمون رو بدیم و خود برنامه بره از سایت دامنه ها رو برداره. من خودمم برنامه نویس حرفه ای نیستم ولی میدونم که با کتابخونه پانداس و دستور read_html میشه جدول های موجود در سایت رو خوند. در مورد بسته شدن شل باید بگم که من خودم اینجوری برنامه رو ران می کنم: میرم پوشه مسیر برنامه و اون بالا که آدرس پوشه هست رو پاک می کنم و میزنم cmd بعد دستور زیر رو مینوسم: python script_name اون script_name همون اسم فایل اسکریپت هست و بعد برنامه ران میشه. برای من تا برنامه تموم نشده صفحه بسته نمیشه.
> 
> منم همین هارو زدم نشده متاسفانه

این مشکل رو خیلی ها داشتن برای کپی کردن.

از مرورگر کروم استفاده کنید برای کپی کردن.

حتما رسیدگی میکنم که این مشکل رو حل کنم

**Comment by amg9898** [comment]
> > > > من اسپیس هم پاک کردم متاسفانه شل تا اسم فایل رو میزنم بسته میشه
> > > 
> > > 
> > > ببین من کل فاصله بین آی پی و دامنه رو پاک نمیکنم. به اندازه یه تب نگه میدارم. یعنی برا من اینجوریه که وقتی از سایت میریزم تو تکست، یدونه اسپیس و یدونه تب داره که من فقط اون اسپیس رو پاک میکنم. به نظرم نویسنده کد میتونه برنامه رو اینجوری بنویسه که ما فقط آی پی سرورمون رو بدیم و خود برنامه بره از سایت دامنه ها رو برداره. من خودمم برنامه نویس حرفه ای نیستم ولی میدونم که با کتابخونه پانداس و دستور read_html میشه جدول های موجود در سایت رو خوند. در مورد بسته شدن شل باید بگم که من خودم اینجوری برنامه رو ران می کنم: میرم پوشه مسیر برنامه و اون بالا که آدرس پوشه هست رو پاک می کنم و میزنم cmd بعد دستور زیر رو مینوسم: python script_name اون script_name همون اسم فایل اسکریپت هست و بعد برنامه ران میشه. برای من تا برنامه تموم نشده صفحه بسته نمیشه.
> > 
> > 
> > منم همین هارو زدم نشده متاسفانه
> 
> این مشکل رو خیلی ها داشتن برای کپی کردن.
> 
> از مرورگر کروم استفاده کنید برای کپی کردن.
> 
> حتما رسیدگی میکنم که این مشکل رو حل کنم


از کروم استفاده کردم اوکی شد الان نیم ساعته رو 83 ردصد جستجو مونده چه کنم>؟

**Comment by Shakin111** [comment]
بعد از این  مرحله:

**Comment by YamlEngineer** [comment]
برای ساخت این فایل میتونید یه فایلی بسازید به اسم domains.txt و دامنه هارو پشت هم بزارید برای مثال
```
example.com
google.com
```
بعد این اسکریپت رو اجرا کنید و اخرش فایلی بهتون میده که بتونید با اسکریپت اجراش کنید
```py
from nslookup import Nslookup

dns_query = Nslookup()
with open("domains.txt") as domains:
  for domain in domains:
    ips_record = dns_query.dns_lookup(domain.strip())
    if len(ips_record.answer) == 1:
        result = open('result.txt', 'a')
        result.write(f"{ips_record.answer[0]}   {domain.strip()}\n")
        result.close()
```
از این اسکریپت میتونید برای ساخت کاستوم دامین ها هم استفاده کنید
در ضمن وقتی دامینی میزارید حتما چک میکنه که a record داره یا نه
@NoAnyNameForMe

**Comment by masterj3y** [comment]
> بعد از این مرحله: "از شما پرسیده میشود بعد از پیدا کردن چند دامنه سالم اسکریپت متوقف شود" بدون اسکن نتیجه به این صورت درمیاد:
> 
> +--------+------------------+-------------+ | Domain | Ping Result (ms) | TLS Version | +--------+------------------+-------------+ +--------+------------------+-------------+
> 
> Successful Domains (TLSv1.3): +--------+------------------+-------------+ | Domain | Ping Result (ms) | TLS Version | +--------+------------------+-------------+ +--------+------------------+-------------+ Successful Domains Found: []
> 
> پیش نیازهارو هم چک کردم همه رو، نصب بود

کد زیر رو که توی این تاریخ توی خط ۲۶ هست رو تغییر بده
` match = re.match(r'^([\d.]+)\t*(.+)$', line)‍‍‍‍‍‍` 
به خط زیر
` match = re.match(r'^([\d.]+)\s*(.+)$', line)`
