### ISSUE TITLE
مشکل در تست سرعت

### ISSUE THREAD

**Issue by f4r3ingh75** [NoAnyNameForMe/SNI-Checker#4]
متاسفانه در تعداد دامنه های زیاد برنامه نمیتواند تست سرعت بگیرد. من 169 دامنه رو پیدا کردم ولی نتونستم تست سرعت بگیرم و با ارور زیر مواجه شدم.
HTTP Error 403: Forbidden
برای تمام دامنه ها همین ارور را میداد.
لطفا راهنمایی کنید.

**Comment by NoAnyNameForMe** [comment]
سلام.

به دلیل اینکه در قسمت Speed Test ورژن 1.3 یک سری مشکلات برای تعدادی وجود داشت و برای تعدادی خیر، این قسمت فعلا در کد حذف میشود.

به زودی قسمت Speed Test را با کانفیگ Reality، منتشر میکنم که کانفیگ را با SNI های چک شده تست بگیرد.

کد در گیت هاب جایگزین شد.

از میکنم بابت مشکلاتی که داشت.
