### ISSUE TITLE
Multithreading and some other features 

### ISSUE THREAD

**Issue by SajjadSedaqat** [NoAnyNameForMe/SNI-Checker#5]
سلام خسته نباشید 
واقعا ممنون بابت کار عالیتون کلی زحمت رو کم می کنه  
فقط پیشنهاداتی داشتم 
1 - اگه امکانش هست multithreading رو هم اضافه کنید
2 - اگه  امکانش هست قابلیتی رو اضافه کنید که بشه بعد 
مقداری چک کردن پرسه رو متوقف کرد و از همون مقدار نتیجه بدست اومده استفاده کرد

3 - یا مثلا این آپشن رو داشته باشه که بگیم اگه صدتا ریزالت زیر این مقدار پینگ پیدا شد متوقف شه 
3 - 2- یا هردو 
4-اگه امکانش هست ریزالت جوری زخیره بشه که بتونیم واسه چک کردن دباره ازش استفاده کنیم عالی میشه

5 -  اگه میشد قابلیتی اضافه بشه از ریزالت قبلی فقط اسپید تست بگیریم خیلی عالی بود

بازم تشکر 🙏🙏🙏🙏🙏🙏

**Comment by NoAnyNameForMe** [comment]
با سلام.
در ورژن 1.4 مشکلات و امکانات اضافه شد.
