### ISSUE TITLE
Add Maximum Responde Time

### ISSUE THREAD

**Issue by vahidx4r4x** [NoAnyNameForMe/SNI-Checker#6]
سلام
تشکر از برنامه ی کاربردی
برنامه یه مشکلی که داره اینه که روی یه‌سری از دامنه‌ها خیلی صبر می‌کنه برای تست
لطفا یه تایمر تو برنامه اضافه کن که اگه مثلا دامنه تا 3 ثانیه responde نداشت بره برای تست دامنه‌ی بعدی

تشکر

**Comment by NoAnyNameForMe** [comment]
با سلام.
در ورژن 1.4 مشکل برطرف شد.
